MOTD = "Welcome %s! This is the default MOTD."
JOIN_MSG = "Player %s just joined."
LEAVE_MSG = "Player %s just left."
REVIVE_MSG = "Like an phonix %s raises from the ashes."
DEATH_MSG = "%s left this world :("
